doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: '%kernel.debug%'
# doctrine_migrations:
#     migrations_paths:
#         "App\\Migrations": "src/Migrations"
#         'AnotherApp\Migrations': '/path/to/other/migrations'