vich_uploader:
    db_driver: orm

    mappings:
        sites:
            uri_prefix: /uploads/sites
            upload_destination: '%kernel.project_dir%/public/uploads/sites'
            # namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            # delete_on_update: false
            # delete_on_remove: false
        # topos:
        #     uri_prefix: /uploads/topos
        #     upload_destination: '%kernel.project_dir%/public/uploads/topos'
